### ISSUE TITLE
RNNs are not compatible with deeplay Layers

### ISSUE THREAD

**Issue by JesusPinedaC** [DeepTrackAI/deeplay#34]
The problem is that argspec = self.get_argspec() in dl.Layers, when applied on the torch recurrent layer, does not correctly access the __init__ input parameters. The reason is that the __init__ method of this family of layers is taged as @overload which makes it difficult to access positional arguments correctly.

**Comment by JesusPinedaC** [comment]
I am currectly working on this, but any input is welcome!

**Comment by BenjaminMidtvedt** [comment]
@JesusPinedaC Could describe the actual issue? Like, what code does not behave as you expect and provide minimal examples to reproduce

**Comment by JesusPinedaC** [comment]
## Problem 1
The first problem is exactly what [@Henrik-KM](https://github.com/Henrik-KM) mentioned in [this GitHub issue](https://github.com/DeepTrackAI/deeplay/issues/24). For example, when defining a layer as follows:

```python
layer = dl.Layer(nn.RNN, 2, 64)
print(layer)
```

it prints:
```python
# Layer[RNN](args=2, kwargs=64)
```

Further, when trying to build the layer
```python
layer.build()
```
raises the error:
```python
# TypeError: __init__() got an unexpected keyword argument 'args'
```

This bug was supposed to be solved by the pull request https://github.com/DeepTrackAI/deeplay/pull/25. However the problem persists. I have carefully checked that I updated the develop branch in my local repo. But please double check!

## Problem 2

The second problem arises when using configure(). The Layer does not recognize the available configurables from nn.RNN or any other torch RNN layer. For instance:

```python
layer.configure(bidirectional=True)
```
 results in the error:
```python
ValueError: Unknown configurable bidirectional for Layer. Available configurables are {'classtype'}.
```

I have added these cases in the unit tests for the pull request https://github.com/DeepTrackAI/deeplay/pull/35

**Comment by BenjaminMidtvedt** [comment]
Ok. Problem 2 is expected. I think best is to solve it by removing configure restrictions of there's a keyword variadic.
Problem 1 should be treated separately. It actually works as expected, but erroneously gets a few extra arguments inserted.
