### ISSUE TITLE
 Need for a more "standard" way to define final models in Deeplay?

### ISSUE THREAD

**Issue by JesusPinedaC** [DeepTrackAI/deeplay#39]
After discussing with some of you, we agreed that there is a need for a simpler and more standard way to define final models in Deeplay. This would allow users to directly specify model attributes or layers during model definition.

The proposed solution is to create a folder within Deeplay called "models." Here, we would define functions that implement standard models. This way, users, especially newcomers, can easily call and use models without needing to delve into more complex Deeplay functionalities.

 I believe this approach makes sense for the book and improves user ease. It also helps to clarify the distinction between "components" and "models" in Deeplay, which is currently somewhat ambiguous.

Here's an example for an RNN:

```python
def RecurrentNN(
    in_features,
    out_features,
    hidden_sizes=[...],
    bidirectional=False,
    layer_type="LSTM",
   # more paremeters
):
    if layer_type == "LSTM":
        layer = nn.LSTM
    else:
        # Handle other layer types if needed

    rnn = dl.components.RecurrentNeuralNetwork(
        in_features,
        hidden_sizes
        # other parameters
    )
    rnn.blocks.layer.configure(layer, bidirectional=bidirectional, #other parameters)

    dense_top = dl.components.MultiLayerPerceptron(#parameters)

    return dl.sequential(rnn, dense_top)
```

The function would return a DeeplayModule that remains customizable for more advanced users!

What do you think @giovannivolpe @Henrik-KM  @cmanzo  @BenjaminMidtvedt  @HarshithBachimanchi ?

**Comment by Henrik-KM** [comment]
I discussed this with Jesus, and think this is a very nice solution! It solves the problem of clearly defining the difference between architectures/models (like u-net) and components (like cnn). It also lets a developer define new models using components in a very deeplay-like way.

**Comment by cmanzo** [comment]
I agree, in this way, users can start from models (where they only define a few parameters) and progressively explore more advanced options.

**Comment by giovannivolpe** [comment]
I also like it.
