### ISSUE TITLE
Lowercase Module Names

### ISSUE THREAD

**Issue by giovannivolpe** [DeepTrackAI/deeplay#42]
According to PEP 8, module names should be lowercase. Shall we change this consistently in deeplay?

**Comment by cmanzo** [comment]
I think we should

**Comment by BenjaminMidtvedt** [comment]
Which modules are not already lower case? 

Edit: ok the block/PLAN etc? I'm ok with changing those to lower case.

**Comment by cmanzo** [comment]
Blocks are now lowercase in PR #40

**Comment by cmanzo** [comment]
Fixed in PR #40
