### ISSUE TITLE
Syntax for slice selector for direct vs child.

### ISSUE THREAD

**Issue by BenjaminMidtvedt** [DeepTrackAI/deeplay#61]
I'm about to introduce a powerful new system for selecting which submodules to configure. It's based on `__getitem__`. The idea is to introduce powerful syntax to quickly select all items one wants to configure. I will first introduce the issue and then explain how the syntax works. 

## What do I need input on?

Consider the following two statements:
```py
selection_1 = model[..., "blocks", 0:2]
selection_2 = model[..., "pool", 0:2]
```

Intuitively one would imagine that the first syntax would select the first two items of the list blocks. This means that `slice` should select the _children_ of the previous selection.

However, that doesn't work for the second syntax. One does not want to select the first two children of every "pool" layer. One likely wants to select the first 2 "pool" layers. 

I think the best solution is to have slices work select the children of the previous selection and introduce an alternative syntax for slicing the current selection directly. However, I'm not sure what that alternative syntax would be. This is what I need input on.

One idea is to have a string syntax like: `model[..., "pool>0:2"]`. But I'm very open to other suggestions and ideas.

## What can be done

Consider the `cnn`. It has a child `blocks` with several children. Each child has the attributes `pool`, `layer`, `activation`, `normalization`.

- `cnn["blocks"]` would select the list of blocks. Equivalent to `cnn.blocks`
- `cnn["blocks", 0]` would select the first block of blocks. Equivalent to `cnn.blocks[0]`.
- `cnn[..., "layer"]` would select every module named `layer`. Equivalent to `block.layer for block in cnn.blocks`
- `cnn["blocks", 0, ...]` would select every child of the first block. Equivalent to `[cnn.blocks[0].pool, cnn.blocks[0].layer, cnn.blocks[0].activation, cnn.blocks[0].normalization]`
-
you can of course mix and match the syntaxes. `cnn[:, :, "layer"]`, `cnn[..., "layer", ...]` etc.

**Comment by giovannivolpe** [comment]
Sounds good, what about the syntax `model[..., "pool[0:2]"]`. This seems more natural within Python

**Comment by BenjaminMidtvedt** [comment]
> Sounds good, what about the syntax `model[..., "pool[0:2]"]`. This seems more natural within Python

I was considering this as well yeah. My concern was that it intuitively looks like it's slicing the children. Like `model[..., "blocks[0:2]"]` really looks like it's selecting the first two blocks, not that it's selecting the first two modules named `blocks`.

**Comment by BenjaminMidtvedt** [comment]
> Sounds good, what about the syntax `model[..., "pool[0:2]"]`. This seems more natural within Python

@giovannivolpe I was considering this as well yeah. My concern was that it intuitively looks like it's slicing the children. Like `model[..., "blocks[0:2]"]` really looks like it's selecting the first two blocks, not that it's selecting the first two modules named `blocks`.

**Comment by giovannivolpe** [comment]
@BenjaminMidtvedt I see your point.
What about `model[..., "{0:2}blocks"]`

**Comment by giovannivolpe** [comment]
let's go with this `model[..., "blocks#0:2"]`
